version: "3"

networks:
  course-network:

services:
  postgresdb:
    image: postgres
    restart: on-failure
    networks:
      - course-network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 100

  app:
    build:
      context: .
      dockerfile: App.dockerfile
    restart: on-failure
    networks:
      - course-network
    ports:
      - "8080:8080"
    depends_on:
      postgresdb:
        condition: service_healthy
