version: "3"

networks:
  devspark-network:

services:
  mongodb:
    image: mongo
    restart: on-failure
    networks:
      devspark-network:
    ports:
      - "27017:27017"

  server:
    build: .
    restart: on-failure
    networks:
      devspark-network:
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
