version: "3"

networks:
  course-network:

services:
  postgresdb:
    image: postgres
    restart: on-failure
    networks:
      course-network:
    ports:
      - "5432:5432"

  server:
    build: .
    restart: on-failure
    networks:
      course-network:
    ports:
      - "8080:8080"
    depends_on:
      - postgresdb
