version: '3'

networks:
  metrics:

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./metrics/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.listen-address=:9090"
    ports:
      - "9090:9090"
    networks:
      - metrics

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - metrics
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_SERVER_HTTP_PORT=3000
    volumes:
      - ./metrics/provisioning:/etc/grafana/provisioning
      - ./metrics/dashboards:/var/lib/grafana/dashboards