{
 "title": "My Dashboard",
 "panels": [
  {
   "title": "Average Duration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM http_req_duration WHERE $timeFilter "
    }
   ]
  },
  {
   "title": "Percentiles",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT percentile(\"value\", 50) AS \"p50\", percentile(\"value\", 75) AS \"p75\", percentile(\"value\", 90) AS \"p90\", percentile(\"value\", 95) AS \"p95\", percentile(\"value\", 99) AS \"p99\" FROM \"http_req_duration\" WHERE $timeFilter GROUP BY time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 12 },
   "targets": [
    {
     "query": "SELECT count(\"value\") FROM \"http_req_duration\" WHERE $timeFilter GROUP BY time($interval), \"value\" fill(null)"
    }
   ]
  }
 ]
}